name: django-pymodsecurity

dependencies:
  - django=2.1.2
  - pymodsecurity=0.0.2
  - pytest
  - pytest-runner
  - pytest-mock
  - pytest-xdist
  - pytest-timeout
  - pytest-django
  - yapf
  - isort
  - pylint
  - invoke
