name: django-pymodsecurity

dependencies:
  - django=2.1.2
  - pymodsecurity=0.0.3
  - pytest
  - pytest-runner
  - pytest-mock
  - pytest-xdist
  - pytest-timeout
  - pytest-django
  - pytest-cov
  - yapf
  - isort
  - pylint
  - invoke
